#!/bin/bash

# Diretório do BSPWM
BSPDIR="$HOME/.config/bspwm"

# Exporta Scripts e .local/bin para PATH
export PATH="${PATH}:$BSPDIR/scripts"

# "Desbuga" aplicações em JAVA
export _JAVA_AWT_WM_NONREPARENTING=1

bspc monitor -d 1 2 3 4 5 6 7 8 9 10


bspc config border_width         1.0
bspc config window_gap           5
bspc config split_ratio          0.50
bspc config bottom_padding	 	 0
bspc config top_padding		 	 0

bspc config focused_border_color 	#81a1c1
bspc config normal_border_color 	#0e1415
bspc config active_border_color 	#31363b
bspc config presel_feedback_color 	##31363b

bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config paddingless_monocle	 	true
bspc config single_monocle	 		false
bspc config focus_follows_pointer	true
bspc config presel_feedback			true

# Gerencia janelas de sessões anteriores
bspc wm --adopt-orphans

# Remove regras anteriores
bspc rule -r *:*

# Apps sempre em modo floating
declare -a floating=(kitty-float Lxappearance Arandr Pavucontrol Exo-helper-1 Xfce4-power-manager-settings Yad Onboard 'Firefox:Places' Viewnior feh Nm-connection-editor gnome-calculator)
for i in ${floating[@]}; do
	bspc rule -a $i state=floating follow=on focus=on; done


# Matar o que está em execução
killall -9 xfce4-power-manager bspc ksuperkey

# Autostart

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &
# bigbashview -w fixed -n "Atalhos BSPWM" -t gtk -s 900x900 $BSPDIR/atalhos/index.html & 
xsetroot -cursor_name left_ptr
numlockx on
xfce4-power-manager &
# random_wallpaper
set_wallpaper
bspcomp
bspdunst
bspfloat &
bspbar




