#!/bin/bash

##
# Executar Kitty com a configuração do BSPWM

# Diretório do BSPWM
DIR="$HOME/.config/bspwm"
# Arquivo de configuração Kitty
CONFIG="$DIR/kitty/kitty.conf"

if [ "$1" == "--float" ]; then
	kitty --class 'kitty-float' -c "$CONFIG"
elif [ "$1" == "--full" ]; then
	kitty --class 'Fullscreen' -c "$CONFIG" \
			  --start-as=fullscreen \
			  -o background_opacity=0.95 \
			  -o font_size=16.0 
	
else
	kitty -c "$CONFIG"
fi
